### ISSUE TITLE
Sync failed

### ISSUE THREAD

**Issue by jluttine** [WooKeyWallet/monero-wallet-android-app#5]
No matter which remote node I choose, I get "Sync failed" error and "No Networks Found" message. I'm using the version from F-Droid. Any ideas what's wrong?

**Comment by NeoChen1024** [comment]
That's because WooKey hasn't update the RPC version

**Comment by blkvlk** [comment]
What to do i can not sync version from f droid my money lost please hrlp

**Comment by WooKeyWallet** [comment]
> What to do i can not sync version from f droid my money lost please hrlp

F-Droid not supported now, please use Google Play or Github or website
